/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as CitizenHomeRouteImport } from './routes/citizen.home'
import { Route as CitizenImpactRouteImport } from './routes/citizen.impact'
import { Route as CitizenProfileRouteImport } from './routes/citizen.profile'
import { Route as CitizenReportRouteImport } from './routes/citizen.report'
import { Route as CitizenScannerRouteImport } from './routes/citizen.scanner'
import { Route as CorporateDashboardRouteImport } from './routes/corporate.dashboard'
import { Route as CorporateEvidenceRouteImport } from './routes/corporate.evidence'
import { Route as MunicipalAnalyticsRouteImport } from './routes/municipal.analytics'
import { Route as MunicipalDashboardRouteImport } from './routes/municipal.dashboard'
import { Route as MunicipalHotspotsRouteImport } from './routes/municipal.hotspots'
import { Route as MunicipalIssuesRouteImport } from './routes/municipal.issues'
import { Route as MunicipalMapRouteImport } from './routes/municipal.map'
import { Route as MunicipalReportsRouteImport } from './routes/municipal.reports'
import { Route as MunicipalRoutesRouteImport } from './routes/municipal.routes'
import { Route as MunicipalSettingsRouteImport } from './routes/municipal.settings'
import { Route as NgoDashboardRouteImport } from './routes/ngo.dashboard'
import { Route as NgoVerificationRouteImport } from './routes/ngo.verification'
import { Route as CitizenCampaignsIndexRouteImport } from './routes/citizen.campaigns.index'
import { Route as CitizenCampaignsIdRouteImport } from './routes/citizen.campaigns.$id'
import { Route as CorporateCampaignsIdRouteImport } from './routes/corporate.campaigns.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenHomeRoute = CitizenHomeRouteImport.update({
  id: '/citizen/home',
  path: '/citizen/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenImpactRoute = CitizenImpactRouteImport.update({
  id: '/citizen/impact',
  path: '/citizen/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenProfileRoute = CitizenProfileRouteImport.update({
  id: '/citizen/profile',
  path: '/citizen/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenReportRoute = CitizenReportRouteImport.update({
  id: '/citizen/report',
  path: '/citizen/report',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenScannerRoute = CitizenScannerRouteImport.update({
  id: '/citizen/scanner',
  path: '/citizen/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateDashboardRoute = CorporateDashboardRouteImport.update({
  id: '/corporate/dashboard',
  path: '/corporate/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateEvidenceRoute = CorporateEvidenceRouteImport.update({
  id: '/corporate/evidence',
  path: '/corporate/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const MunicipalAnalyticsRoute = MunicipalAnalyticsRouteImport.update({
  id: '/municipal/analytics',
  path: '/municipal/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const MunicipalDashboardRoute = MunicipalDashboardRouteImport.update({
  id: '/municipal/dashboard',
  path: '/municipal/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MunicipalHotspotsRoute = MunicipalHotspotsRouteImport.update({
  id: '/municipal/hotspots',
  path: '/municipal/hotspots',
  getParentRoute: () => rootRouteImport,
} as any)
const MunicipalIssuesRoute = MunicipalIssuesRouteImport.update({
  id: '/municipal/issues',
  path: '/municipal/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const MunicipalMapRoute = MunicipalMapRouteImport.update({
  id: '/municipal/map',
  path: '/municipal/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MunicipalReportsRoute = MunicipalReportsRouteImport.update({
  id: '/municipal/reports',
  path: '/municipal/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MunicipalRoutesRoute = MunicipalRoutesRouteImport.update({
  id: '/municipal/routes',
  path: '/municipal/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const MunicipalSettingsRoute = MunicipalSettingsRouteImport.update({
  id: '/municipal/settings',
  path: '/municipal/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NgoDashboardRoute = NgoDashboardRouteImport.update({
  id: '/ngo/dashboard',
  path: '/ngo/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NgoVerificationRoute = NgoVerificationRouteImport.update({
  id: '/ngo/verification',
  path: '/ngo/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenCampaignsIndexRoute = CitizenCampaignsIndexRouteImport.update({
  id: '/citizen/campaigns/',
  path: '/citizen/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenCampaignsIdRoute = CitizenCampaignsIdRouteImport.update({
  id: '/citizen/campaigns/$id',
  path: '/citizen/campaigns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateCampaignsIdRoute = CorporateCampaignsIdRouteImport.update({
  id: '/corporate/campaigns/$id',
  path: '/corporate/campaigns/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/citizen/home': typeof CitizenHomeRoute
  '/citizen/impact': typeof CitizenImpactRoute
  '/citizen/profile': typeof CitizenProfileRoute
  '/citizen/report': typeof CitizenReportRoute
  '/citizen/scanner': typeof CitizenScannerRoute
  '/corporate/dashboard': typeof CorporateDashboardRoute
  '/corporate/evidence': typeof CorporateEvidenceRoute
  '/municipal/analytics': typeof MunicipalAnalyticsRoute
  '/municipal/dashboard': typeof MunicipalDashboardRoute
  '/municipal/hotspots': typeof MunicipalHotspotsRoute
  '/municipal/issues': typeof MunicipalIssuesRoute
  '/municipal/map': typeof MunicipalMapRoute
  '/municipal/reports': typeof MunicipalReportsRoute
  '/municipal/routes': typeof MunicipalRoutesRoute
  '/municipal/settings': typeof MunicipalSettingsRoute
  '/ngo/dashboard': typeof NgoDashboardRoute
  '/ngo/verification': typeof NgoVerificationRoute
  '/citizen/campaigns/$id': typeof CitizenCampaignsIdRoute
  '/corporate/campaigns/$id': typeof CorporateCampaignsIdRoute
  '/citizen/campaigns/': typeof CitizenCampaignsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/citizen/home': typeof CitizenHomeRoute
  '/citizen/impact': typeof CitizenImpactRoute
  '/citizen/profile': typeof CitizenProfileRoute
  '/citizen/report': typeof CitizenReportRoute
  '/citizen/scanner': typeof CitizenScannerRoute
  '/corporate/dashboard': typeof CorporateDashboardRoute
  '/corporate/evidence': typeof CorporateEvidenceRoute
  '/municipal/analytics': typeof MunicipalAnalyticsRoute
  '/municipal/dashboard': typeof MunicipalDashboardRoute
  '/municipal/hotspots': typeof MunicipalHotspotsRoute
  '/municipal/issues': typeof MunicipalIssuesRoute
  '/municipal/map': typeof MunicipalMapRoute
  '/municipal/reports': typeof MunicipalReportsRoute
  '/municipal/routes': typeof MunicipalRoutesRoute
  '/municipal/settings': typeof MunicipalSettingsRoute
  '/ngo/dashboard': typeof NgoDashboardRoute
  '/ngo/verification': typeof NgoVerificationRoute
  '/citizen/campaigns/$id': typeof CitizenCampaignsIdRoute
  '/corporate/campaigns/$id': typeof CorporateCampaignsIdRoute
  '/citizen/campaigns': typeof CitizenCampaignsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/citizen/home': typeof CitizenHomeRoute
  '/citizen/impact': typeof CitizenImpactRoute
  '/citizen/profile': typeof CitizenProfileRoute
  '/citizen/report': typeof CitizenReportRoute
  '/citizen/scanner': typeof CitizenScannerRoute
  '/corporate/dashboard': typeof CorporateDashboardRoute
  '/corporate/evidence': typeof CorporateEvidenceRoute
  '/municipal/analytics': typeof MunicipalAnalyticsRoute
  '/municipal/dashboard': typeof MunicipalDashboardRoute
  '/municipal/hotspots': typeof MunicipalHotspotsRoute
  '/municipal/issues': typeof MunicipalIssuesRoute
  '/municipal/map': typeof MunicipalMapRoute
  '/municipal/reports': typeof MunicipalReportsRoute
  '/municipal/routes': typeof MunicipalRoutesRoute
  '/municipal/settings': typeof MunicipalSettingsRoute
  '/ngo/dashboard': typeof NgoDashboardRoute
  '/ngo/verification': typeof NgoVerificationRoute
  '/citizen/campaigns/$id': typeof CitizenCampaignsIdRoute
  '/corporate/campaigns/$id': typeof CorporateCampaignsIdRoute
  '/citizen/campaigns/': typeof CitizenCampaignsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/auth/login'
    | '/auth/register'
    | '/citizen/home'
    | '/citizen/impact'
    | '/citizen/profile'
    | '/citizen/report'
    | '/citizen/scanner'
    | '/corporate/dashboard'
    | '/corporate/evidence'
    | '/municipal/analytics'
    | '/municipal/dashboard'
    | '/municipal/hotspots'
    | '/municipal/issues'
    | '/municipal/map'
    | '/municipal/reports'
    | '/municipal/routes'
    | '/municipal/settings'
    | '/ngo/dashboard'
    | '/ngo/verification'
    | '/citizen/campaigns/$id'
    | '/corporate/campaigns/$id'
    | '/citizen/campaigns/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/auth/login'
    | '/auth/register'
    | '/citizen/home'
    | '/citizen/impact'
    | '/citizen/profile'
    | '/citizen/report'
    | '/citizen/scanner'
    | '/corporate/dashboard'
    | '/corporate/evidence'
    | '/municipal/analytics'
    | '/municipal/dashboard'
    | '/municipal/hotspots'
    | '/municipal/issues'
    | '/municipal/map'
    | '/municipal/reports'
    | '/municipal/routes'
    | '/municipal/settings'
    | '/ngo/dashboard'
    | '/ngo/verification'
    | '/citizen/campaigns/$id'
    | '/corporate/campaigns/$id'
    | '/citizen/campaigns'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/auth/login'
    | '/auth/register'
    | '/citizen/home'
    | '/citizen/impact'
    | '/citizen/profile'
    | '/citizen/report'
    | '/citizen/scanner'
    | '/corporate/dashboard'
    | '/corporate/evidence'
    | '/municipal/analytics'
    | '/municipal/dashboard'
    | '/municipal/hotspots'
    | '/municipal/issues'
    | '/municipal/map'
    | '/municipal/reports'
    | '/municipal/routes'
    | '/municipal/settings'
    | '/ngo/dashboard'
    | '/ngo/verification'
    | '/citizen/campaigns/$id'
    | '/corporate/campaigns/$id'
    | '/citizen/campaigns/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  CitizenHomeRoute: typeof CitizenHomeRoute
  CitizenImpactRoute: typeof CitizenImpactRoute
  CitizenProfileRoute: typeof CitizenProfileRoute
  CitizenReportRoute: typeof CitizenReportRoute
  CitizenScannerRoute: typeof CitizenScannerRoute
  CorporateDashboardRoute: typeof CorporateDashboardRoute
  CorporateEvidenceRoute: typeof CorporateEvidenceRoute
  MunicipalAnalyticsRoute: typeof MunicipalAnalyticsRoute
  MunicipalDashboardRoute: typeof MunicipalDashboardRoute
  MunicipalHotspotsRoute: typeof MunicipalHotspotsRoute
  MunicipalIssuesRoute: typeof MunicipalIssuesRoute
  MunicipalMapRoute: typeof MunicipalMapRoute
  MunicipalReportsRoute: typeof MunicipalReportsRoute
  MunicipalRoutesRoute: typeof MunicipalRoutesRoute
  MunicipalSettingsRoute: typeof MunicipalSettingsRoute
  NgoDashboardRoute: typeof NgoDashboardRoute
  NgoVerificationRoute: typeof NgoVerificationRoute
  CitizenCampaignsIdRoute: typeof CitizenCampaignsIdRoute
  CorporateCampaignsIdRoute: typeof CorporateCampaignsIdRoute
  CitizenCampaignsIndexRoute: typeof CitizenCampaignsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/home': {
      id: '/citizen/home'
      path: '/citizen/home'
      fullPath: '/citizen/home'
      preLoaderRoute: typeof CitizenHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/impact': {
      id: '/citizen/impact'
      path: '/citizen/impact'
      fullPath: '/citizen/impact'
      preLoaderRoute: typeof CitizenImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/profile': {
      id: '/citizen/profile'
      path: '/citizen/profile'
      fullPath: '/citizen/profile'
      preLoaderRoute: typeof CitizenProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/report': {
      id: '/citizen/report'
      path: '/citizen/report'
      fullPath: '/citizen/report'
      preLoaderRoute: typeof CitizenReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/scanner': {
      id: '/citizen/scanner'
      path: '/citizen/scanner'
      fullPath: '/citizen/scanner'
      preLoaderRoute: typeof CitizenScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate/dashboard': {
      id: '/corporate/dashboard'
      path: '/corporate/dashboard'
      fullPath: '/corporate/dashboard'
      preLoaderRoute: typeof CorporateDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate/evidence': {
      id: '/corporate/evidence'
      path: '/corporate/evidence'
      fullPath: '/corporate/evidence'
      preLoaderRoute: typeof CorporateEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/municipal/analytics': {
      id: '/municipal/analytics'
      path: '/municipal/analytics'
      fullPath: '/municipal/analytics'
      preLoaderRoute: typeof MunicipalAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/municipal/dashboard': {
      id: '/municipal/dashboard'
      path: '/municipal/dashboard'
      fullPath: '/municipal/dashboard'
      preLoaderRoute: typeof MunicipalDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/municipal/hotspots': {
      id: '/municipal/hotspots'
      path: '/municipal/hotspots'
      fullPath: '/municipal/hotspots'
      preLoaderRoute: typeof MunicipalHotspotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/municipal/issues': {
      id: '/municipal/issues'
      path: '/municipal/issues'
      fullPath: '/municipal/issues'
      preLoaderRoute: typeof MunicipalIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/municipal/map': {
      id: '/municipal/map'
      path: '/municipal/map'
      fullPath: '/municipal/map'
      preLoaderRoute: typeof MunicipalMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/municipal/reports': {
      id: '/municipal/reports'
      path: '/municipal/reports'
      fullPath: '/municipal/reports'
      preLoaderRoute: typeof MunicipalReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/municipal/routes': {
      id: '/municipal/routes'
      path: '/municipal/routes'
      fullPath: '/municipal/routes'
      preLoaderRoute: typeof MunicipalRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/municipal/settings': {
      id: '/municipal/settings'
      path: '/municipal/settings'
      fullPath: '/municipal/settings'
      preLoaderRoute: typeof MunicipalSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ngo/dashboard': {
      id: '/ngo/dashboard'
      path: '/ngo/dashboard'
      fullPath: '/ngo/dashboard'
      preLoaderRoute: typeof NgoDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ngo/verification': {
      id: '/ngo/verification'
      path: '/ngo/verification'
      fullPath: '/ngo/verification'
      preLoaderRoute: typeof NgoVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/campaigns/': {
      id: '/citizen/campaigns/'
      path: '/citizen/campaigns'
      fullPath: '/citizen/campaigns/'
      preLoaderRoute: typeof CitizenCampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/campaigns/$id': {
      id: '/citizen/campaigns/$id'
      path: '/citizen/campaigns/$id'
      fullPath: '/citizen/campaigns/$id'
      preLoaderRoute: typeof CitizenCampaignsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate/campaigns/$id': {
      id: '/corporate/campaigns/$id'
      path: '/corporate/campaigns/$id'
      fullPath: '/corporate/campaigns/$id'
      preLoaderRoute: typeof CorporateCampaignsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  CitizenHomeRoute: CitizenHomeRoute,
  CitizenImpactRoute: CitizenImpactRoute,
  CitizenProfileRoute: CitizenProfileRoute,
  CitizenReportRoute: CitizenReportRoute,
  CitizenScannerRoute: CitizenScannerRoute,
  CorporateDashboardRoute: CorporateDashboardRoute,
  CorporateEvidenceRoute: CorporateEvidenceRoute,
  MunicipalAnalyticsRoute: MunicipalAnalyticsRoute,
  MunicipalDashboardRoute: MunicipalDashboardRoute,
  MunicipalHotspotsRoute: MunicipalHotspotsRoute,
  MunicipalIssuesRoute: MunicipalIssuesRoute,
  MunicipalMapRoute: MunicipalMapRoute,
  MunicipalReportsRoute: MunicipalReportsRoute,
  MunicipalRoutesRoute: MunicipalRoutesRoute,
  MunicipalSettingsRoute: MunicipalSettingsRoute,
  NgoDashboardRoute: NgoDashboardRoute,
  NgoVerificationRoute: NgoVerificationRoute,
  CitizenCampaignsIdRoute: CitizenCampaignsIdRoute,
  CorporateCampaignsIdRoute: CorporateCampaignsIdRoute,
  CitizenCampaignsIndexRoute: CitizenCampaignsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
